version: "3.8"

services:
  wiremock:
    image: sheyenrath/wiremock.net
    ports:
      - "9091:80"
    volumes:
      - ./wiremock/mappings:/app/__admin/mappings
    command: ["--ReadStaticMappings", "true", "--WireMockLogger", "WireMockConsoleLogger"]
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
    volumes:
      - ./mysql_data:/var/lib/mysql